---
sdkversion: 5.1.0
name: appforum-rho-full
version: '1.0'
vendor: rhomobile
build: debug
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator8.2
  provisionprofile: ''
  codesignidentity: iPhone Developer
  entitlements: ''
  BundleIdentifier: com.rhomobile.appforum-rho-full
  BundleURLScheme: appforum-rho-full
  production:
    ipa_itunesartwork_image: ./production/iTunesArtwork.png
wp8:
  productid: 3343cef1-27ba-0133-cb39-00155df124be
android:
  version: 2.3.3
  logcatFilter: APP:I StrictMode:I DEBUG:I *:E
wm: ''
win32:
  deployqt: '1'
  deploymsvc: '1'
extensions:
- rhoconnect-client
- lightsensor
- cordovabarcode
rhobundle:
  exclude_items:
  - thumb.db
#app_type: rhoelements
capabilities: []
